/** @type {import('next').NextConfig} */
const nextConfig = {
  // output: 'export',
  images: {
    // Every image is a local, pre-cropped file under public/images, generated by
    // scripts/generate-images.mjs at the exact size each slot renders at, so there is
    // nothing to optimise at request time and no remote host to allow.
    unoptimized: true,
  }
}

module.exports = nextConfig
